# Generated by Django 5.2.1 on 2025-05-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HarmonizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=64)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('location_id', models.CharField(max_length=64)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=16, null=True)),
                ('study_group', models.CharField(blank=True, max_length=64, null=True)),
                ('body_temperature', models.FloatField(blank=True, null=True)),
                ('systolic_bp', models.IntegerField(blank=True, null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, null=True)),
                ('adverse_event', models.CharField(blank=True, max_length=8, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('precipitation', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('air_quality_index', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
